### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by marumari** [google/badssl.com#139]
I have no idea what badssl's license is, despite all these contributions.  @lgarron, could you please add one?

Thanks!

**Comment by Hoverbear** [comment]
Actually he can't without consulting us about our contributions! Currently our code is all copyright our respective persons.

I am fine releasing mine under MIT or any other open source license.

**Comment by marumari** [comment]
Likewise.  I generally work under MPL (for my work stuff), but any open source license is fine by me.

**Comment by lgarron** [comment]
I usually go for MIT.

Other committers include @rugk ([commits](https://github.com/lgarron/badssl.com/commits/master?author=rugk)), @hotaru2k3 ([commits](https://github.com/lgarron/badssl.com/commits/master?author=hotaru2k3)), and [Richard Barnes](https://github.com/lgarron/badssl.com/commit/76ed15e54ac4388a37960ae67b033732d921fb81).

Since I used significant work time on this project, I should go through the copyright assignment process. II should perhaps move the repo under the Chromium org, which which case we'd need to get everyone to sign the Google CLA.

- @rugk and @hotaru2k3: Are you alright with contributing your commit under the MIT license?

**Comment by lgarron** [comment]
And @marumari  could you poke Richard Barnes?

**Comment by hotaru2k3** [comment]
MIT is fine with me, and the Google CLA looks pretty much like giving Google a license with similar terms to the MIT license plus an explicit patent grant (which only matters if there are patents involved), so I don't think I'd have a problem with it.

**Comment by rugk** [comment]
> @rugk and @hotaru2k3: Would you give consent to contribute your commits under the MIT license?

Yes.

> Everyone: Would you be willing to sign the Google CLA?

In case you really need it. But generally I do not like CLAs so much...

> I should perhaps move the repo under [the Chromium org](https://github.com/chromium)

This would be quite strange as this repo has not mu8ch to do with Chromium.

**Comment by Hoverbear** [comment]
@lgarron I'd rather not sign Google's CLA (They highly discourage new contributions) but will if asked nicely.

**Comment by marumari** [comment]
I too would prefer that it not be moved under Chromium and also that I not sign the CLA.

As far as Richard goes, I think he just moved some files around, so there's not really any need for copyright agreements from him.

**Comment by lgarron** [comment]
Sorry for the long delay, but I've figured out all the parts from the Google side. As you might have noticed, this repo is now under `github.com/google`. I can ask to move it to `github.com/chromium`, but we should first get licensing completely in order.

The project now has an Apache 2 license, which is the default for projects open-sourced by Google.
We also have a Google CLA. I understand that this is a bit of a barrier to contributions, but this turns out to be non-negotiable.
*However*, Mozilla already is on file as agreeing to the Google CLA, so Mozilla and Google employees can both contribute work time to the project. Mozilla folks will either have to be added to `mozilla-google-cla-contributors@mozilla.com` or sign the CLA.

@Hoverbear, are you able to be added to that list? If not, would you mind signing the CLA individually at https://cla.developers.google.com/about/google-individual ?

@rugk and @hotaru2k3 , would you sign the individual CLA, too?

**Comment by Hoverbear** [comment]
@marumari Is there any chance I'd fall under the Mozilla CLA due to MWoS? This would be very acceptable to me.

**Comment by marumari** [comment]
I can check with legal, but it would probably just be easiest if you agreed
to the CLA on your own. It's not the most onerous license or anything.  :)

On Apr 29, 2016, at 8:45 PM, Andrew Hobden <notifications@github.com> wrote:

@marumari <https://github.com/marumari> Is there any chance I'd fall under
the Mozilla CLA due to MWoS? This would be very acceptable to me.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/google/badssl.com/issues/139#issuecomment-215923046>

**Comment by rugk** [comment]
> @rugk and @hotaru2k3 , would you sign the individual CLA, too?

As I already said, yes.

**Comment by lgarron** [comment]
In that case, @rugk, would you please go ahead and do so? I believe that
then we'll have everyone. :-)

**Comment by rugk** [comment]
Done.

**Comment by lgarron** [comment]
Thanks, that makes everyone! :-)
