### ISSUE TITLE
'ssl' is a little archaic. I have badhttps.com, do you want it?

### ISSUE THREAD

**Issue by mikemaccana** [google/badssl.com#172]
Hey Lucas,

Like most of the (non-crap) part of the industry, I've avoided the TLS/SSL discussion (which is mainly by pedantic nerds) entirely by talking about https. https://certsimple.com now uses 'https' almost everywhere, Google Security Blog and Let's Encrypt do too. I suspect https is also more easier to understand as that's what the browser shows.

With that in mind, do you want badhttps.com? I registered it before anyone else could, just let me know and I'll transfer it. 

Mike / CertSimple

**Comment by lgarron** [comment]
Thanks for holding on to it, but I actually chose `badssl.com` on purpose:

- It's shorter and catchier (2 letters shorter, half the syllables).
- It doesn't duplicate the scheme in the domain name. `https://badhttps.com` doesn't look *too* bad, but I think the duplication of `https` can be unnecessarily confusing. This site is meant for testing UI edge cases, and the domain may show up in all sorts of screenshots. We often write test instructions for people who may not know much about what we're doing; I can easily imagine someone misdescribing/misunderstanding an expected behaviour because the domain contains `https`.
- It subtly disparages the term "ssl". `badhttps` sounds like it's saying HTTPS is bad, as if you named your dog HTTPS and your dog left the front door flap open, and you said "*Bad HTTPS*, no treats for you tonight.". ;-)

I usually support  using the term HTTPS instead of TLS/SSL when talking about transport security, but I very consciously chose not to do so here. I hope that's alright.

**Comment by marumari** [comment]
Not to mention that getting the certificates reissued would be both
expensive and time-consuming.  :)

On Jun 29, 2016, at 3:02 PM, Lucas Garron <notifications@github.com> wrote:

Thanks for holding on to it, but I actually chose badssl.com on purpose:

   - It's shorter and catchier (2 letters shorter, half the syllables).
   - It doesn't duplicate the scheme in the domain name.
   https://badhttps.com doesn't look *too* bad, but I think the duplication
   of https can be unnecessarily confusing. This site is meant for testing
   UI edge cases, and the domain may show up in all sorts of screenshots. We
   often write test instructions for people who may not know much about what
   we're doing; I can easily imagine someone misdescribing/misunderstanding an
   expected behaviour because the domain contains https.
   - It subtly disparages the term "ssl". badhttps sounds like it's saying
   HTTPS is bad, as if you named your dog HTTPS and your dog left the front
   door flap open, and you said "*Bad HTTPS*, no treats for you tonight.".
   ;-)

I usually support using the term HTTPS instead of TLS/SSL when talking
about transport security, but I very consciously chose not to do so here. I
hope that's alright.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/badssl.com/issues/172#issuecomment-229471296>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAOEgF5Frsel2usiVSlih2CY5bLy1D69ks5qQs9OgaJpZM4JBPtn>
.

**Comment by lgarron** [comment]
> would be both
> expensive and time-consuming.  :)

Ah, yes. SHA-1 would also be against the Baseline Requirements. ;-)

**Comment by mikemaccana** [comment]
lol excellent point @marumari I remember what it was like thr first time round :^)

**Comment by mikemaccana** [comment]
Fair enough Lucas. Give me a shout when you're in London next and we'll get beer! 😀

**Comment by lgarron** [comment]
> Give me a shout when you're in London next and we'll get beer! 😀

Woah, you're in London?
I'll be there July 18-July 22, how's Wed 20 or Thu 21 for you?

**Comment by mikemaccana** [comment]
Thu 21st it is! Do you want me to get an Infosec  beer posse together?

Get Outlook for iOS




On Thu, Jun 30, 2016 at 9:25 PM +0100, "Lucas Garron" <notifications@github.com> wrote:













Give me a shout when you're in London next and we'll get beer! 😀




Woah, you're in London?

I'll be there July 18-July 22, how's Wed 20 or Thu 21 for you?

**Comment by lgarron** [comment]
> Thu 21st it is! Do you want me to get an Infosec  beer posse together?

I don't drink alcohol, but I'm happy to join with a large glass of whatever refreshing tea-based beverage is in season. :-)

I'll be close to Victoria Station, but I haven't been to London this millennium yet, so I don't know my way around. Any suggestions for a time and place?
